/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aleks' at '11-04-18 11:00' with Gradle 2.14.1
 *
 * @author aleks, @date 11-04-18 11:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
